### ISSUE TITLE
Make namespace optional with default values

### ISSUE THREAD

**Issue by MatteoJoliveau** [karavel-io/platform#20]
Presently every Karavel component needs to have its target namespace injected via `karavel.hcl`.

```hcl
component "external-secrets" {
    namespace = "external-secrets"
}

component "cert-manager" {
    namespace = "cert-manager"
}
```

Given that we have some preferred default values for each components (e.g. all the Grafana stuff goes into `monitoring`, etc) these defaults could be made part of the component Helm chart and the CLI reads these values when omitted in the HCL file.

## Proposed implementation

Make the default namespace a known value in each component's `value.yaml` (e.g. `/namespace`). The CLI will read this known value and use it to set the namespace for the component.

## Checklist

- [x] update karavel CLI to implement this behaviour
- [x] add `namespace` value to [argocd](https://github.com/karavel-io/platform-component-argocd)
- [x] add `namespace` value to [cert-manager](https://github.com/karavel-io/platform-component-cert-manager)
- [x] add `namespace` value to [dex](https://github.com/karavel-io/platform-component-dex)
- [x] add `namespace` value to [external-dns](https://github.com/karavel-io/platform-component-external-dns)
- [x] add `namespace` value to [external-secrets](https://github.com/karavel-io/platform-component-external-secrets)
- [x] add `namespace` value to [gatekeeper](https://github.com/karavel-io/platform-component-gatekeeper)
- [x] add `namespace` value to [goldpinger](https://github.com/karavel-io/platform-component-goldpinger)
- [x] add `namespace` value to [grafana](https://github.com/karavel-io/platform-component-grafana)
- [x] add `namespace` value to [ingress-nginx](https://github.com/karavel-io/platform-component-ingress-nginx)
- [x] add `namespace` value to [loki](https://github.com/karavel-io/platform-component-loki)
- [x] add `namespace` value to [olm](https://github.com/karavel-io/platform-component-olm)
- [x] add `namespace` value to [prometheus](https://github.com/karavel-io/platform-component-prometheus)
- [x] add `namespace` value to [tempo](https://github.com/karavel-io/platform-component-tempo)
- [x] add `namespace` value to [velero](https://github.com/karavel-io/platform-component-velero)
